name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - development

jobs:
  distribution_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Build and distribute app to Firebase
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIRESBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane firebase_distribution
        working-directory: android
